
The following have been reloaded with a version change:
  1) cuda/11.8.0-fasrc01 => cuda/12.4.1-fasrc01
  2) cudnn/8.9.2.26_cuda11-fasrc01 => cudnn/9.1.1.17_cuda12-fasrc01

The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `4`
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[W1214 23:33:37.199795775 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
2024-12-14 23:34:20,214 [INFO] Based on the current allocation process, no modules could be assigned to the following devices due to insufficient memory:
  - 0: 526398464 bytes required
  - 1: 513802240 bytes required
  - 2: 513802240 bytes required
These minimum requirements are specific to this allocation attempt and may vary. Consider increasing the available memory for these devices to at least the specified minimum, or adjusting the model config.
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
2024-12-14 23:34:20,243 [INFO] Based on the current allocation process, no modules could be assigned to the following devices due to insufficient memory:
  - 0: 526398464 bytes required
  - 1: 513802240 bytes required
  - 2: 513802240 bytes required
These minimum requirements are specific to this allocation attempt and may vary. Consider increasing the available memory for these devices to at least the specified minimum, or adjusting the model config.
2024-12-14 23:34:20,251 [INFO] Based on the current allocation process, no modules could be assigned to the following devices due to insufficient memory:
  - 0: 526398464 bytes required
  - 1: 513802240 bytes required
  - 2: 513802240 bytes required
These minimum requirements are specific to this allocation attempt and may vary. Consider increasing the available memory for these devices to at least the specified minimum, or adjusting the model config.
2024-12-14 23:34:20,280 [INFO] Based on the current allocation process, no modules could be assigned to the following devices due to insufficient memory:
  - 0: 526398464 bytes required
  - 1: 513802240 bytes required
  - 2: 513802240 bytes required
These minimum requirements are specific to this allocation attempt and may vary. Consider increasing the available memory for these devices to at least the specified minimum, or adjusting the model config.
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
2024-12-14 23:34:22,041 [INFO] Based on the current allocation process, no modules could be assigned to the following devices due to insufficient memory:
  - 0: 526398464 bytes required
  - 1: 513802240 bytes required
  - 2: 513802240 bytes required
These minimum requirements are specific to this allocation attempt and may vary. Consider increasing the available memory for these devices to at least the specified minimum, or adjusting the model config.
2024-12-14 23:34:22,088 [INFO] Based on the current allocation process, no modules could be assigned to the following devices due to insufficient memory:
  - 0: 526398464 bytes required
  - 1: 513802240 bytes required
  - 2: 513802240 bytes required
These minimum requirements are specific to this allocation attempt and may vary. Consider increasing the available memory for these devices to at least the specified minimum, or adjusting the model config.
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
2024-12-14 23:34:22,148 [INFO] Based on the current allocation process, no modules could be assigned to the following devices due to insufficient memory:
  - 0: 526398464 bytes required
  - 1: 513802240 bytes required
  - 2: 513802240 bytes required
These minimum requirements are specific to this allocation attempt and may vary. Consider increasing the available memory for these devices to at least the specified minimum, or adjusting the model config.
2024-12-14 23:34:22,180 [INFO] Based on the current allocation process, no modules could be assigned to the following devices due to insufficient memory:
  - 0: 526398464 bytes required
  - 1: 513802240 bytes required
  - 2: 513802240 bytes required
These minimum requirements are specific to this allocation attempt and may vary. Consider increasing the available memory for these devices to at least the specified minimum, or adjusting the model config.
[W1214 23:34:24.336484258 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
[W1214 23:34:25.550958270 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
[W1214 23:34:25.551647383 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
[W1214 23:34:25.552868025 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [localhost]:29500 (errno: 97 - Address family not supported by protocol).
2024-12-14 23:34:25,245 [WARNING] Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

Starting epoch 1/10...
Starting epoch 1/10...

Starting epoch 1/10...


Starting epoch 1/10...
[rank3]: Traceback (most recent call last):
[rank3]:   File "/n/holylfs06/LABS/kempner_fellow_emalach/Lab/rli/2281-Project/main.py", line 195, in <module>
[rank3]:     epoch_losses = train_learner_with_target(learner, drafters, target_model, data_loader, 
[rank3]:   File "/n/holylfs06/LABS/kempner_fellow_emalach/Lab/rli/2281-Project/models/training.py", line 51, in train_learner_with_target
[rank3]:     logging.info(f"Processed {step} batches")
[rank3]: NameError: name 'logging' is not defined
[rank2]: Traceback (most recent call last):
[rank2]:   File "/n/holylfs06/LABS/kempner_fellow_emalach/Lab/rli/2281-Project/main.py", line 195, in <module>
[rank2]:     epoch_losses = train_learner_with_target(learner, drafters, target_model, data_loader, 
[rank2]:   File "/n/holylfs06/LABS/kempner_fellow_emalach/Lab/rli/2281-Project/models/training.py", line 51, in train_learner_with_target
[rank2]:     logging.info(f"Processed {step} batches")
[rank2]: NameError: name 'logging' is not defined
[rank1]: Traceback (most recent call last):
[rank1]:   File "/n/holylfs06/LABS/kempner_fellow_emalach/Lab/rli/2281-Project/main.py", line 195, in <module>
[rank1]:     epoch_losses = train_learner_with_target(learner, drafters, target_model, data_loader, 
[rank1]:   File "/n/holylfs06/LABS/kempner_fellow_emalach/Lab/rli/2281-Project/models/training.py", line 51, in train_learner_with_target
[rank1]:     logging.info(f"Processed {step} batches")
[rank1]: NameError: name 'logging' is not defined
[rank0]: Traceback (most recent call last):
[rank0]:   File "/n/holylfs06/LABS/kempner_fellow_emalach/Lab/rli/2281-Project/main.py", line 195, in <module>
[rank0]:     epoch_losses = train_learner_with_target(learner, drafters, target_model, data_loader, 
[rank0]:   File "/n/holylfs06/LABS/kempner_fellow_emalach/Lab/rli/2281-Project/models/training.py", line 51, in train_learner_with_target
[rank0]:     logging.info(f"Processed {step} batches")
[rank0]: NameError: name 'logging' is not defined
[rank0]:[W1214 23:37:41.797400067 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W1214 23:37:43.912987 1849375 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1849880 closing signal SIGTERM
W1214 23:37:43.922299 1849375 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1849881 closing signal SIGTERM
W1214 23:37:43.922464 1849375 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 1849882 closing signal SIGTERM
E1214 23:37:45.165125 1849375 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 1849879) of binary: /n/home13/rli42/conda/envs/2281-project-env/bin/python3.9
Traceback (most recent call last):
  File "/n/home13/rli42/conda/envs/2281-project-env/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/n/home13/rli42/conda/envs/2281-project-env/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/n/home13/rli42/conda/envs/2281-project-env/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/n/home13/rli42/conda/envs/2281-project-env/lib/python3.9/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/n/home13/rli42/conda/envs/2281-project-env/lib/python3.9/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/n/home13/rli42/conda/envs/2281-project-env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/n/home13/rli42/conda/envs/2281-project-env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-14_23:37:43
  host      : holygpu8a13203.rc.fas.harvard.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1849879)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
